### PR TITLE
fix: Add missing build dependencies to devcontainer

### PR DESCRIPTION
**Pull request by iago-veiga**
## Problem
The devcontainer was missing several essential build dependencies, causing compilation to fail at various stages. Some of these dependencies became requirements after PR #1072 introduced QEMU tests:

- QEMU tests failed (missing `qemu-user-static`) - **introduced by PR #1072**
- mdnsd configure failed (missing `pkg-config`)
- ftpd/pure-ftpd autogen failed (missing `automake`, `autoconf`, `libtool`)
- onvif_simple_server json-c compilation failed (missing `cmake`)
- Git submodules not initialized automatically on fresh clones

Additionally, the previous devcontainer update (#1070) accidentally removed many original build packages.

## Solution
- Restored all original Dockerfile packages from upstream
- Added missing dependencies required by QEMU tests and build process:
  - `qemu-user-static`: Required for ARM binary testing (PR #1072)
  - `pkg-config`: Required for mdnsd configure
  - `automake`, `autoconf`, `libtool`: Required for ftpd/pure-ftpd autogen
  - `cmake`: Required for onvif_simple_server json-c compilation
- Added `postCreateCommand` in `devcontainer.json` to automatically initialize git submodules

## Testing
- ✅ Full compilation completes successfully (all 356 files)
- ✅ All modules compile without errors, including QEMU tests
- ✅ Firmware packages generated correctly (~7.4MB each)
- ✅ Git submodules initialize automatically on container creation

## Impact
Developers can now clone the repository and immediately start building without manual dependency installation or submodule initialization. The devcontainer is fully compatible with the QEMU testing framework introduced in PR #1072.

### CODE REVIEW

**Comment by roleoroleo** [comment]
Thank you for your pr.
